//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCostmeticWAD2.DAL.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreStructure
    {
        public string Id { get; set; }
        public int StoreId { get; set; }
        public string EmployeeId { get; set; }
        public string Role { get; set; }
    }
}
